#!/bin/bash

autoreconf -i
./configure --enable-tcmalloc
cd src/third_party/
unzip gperftools-2.1.zip
cd gperftools-2.1/
./configure
make
cd ../../../
make

BASE_DIR=`pwd`
export DYLD_LIBRARY_PATH="${BASE_DIR}/src/third_party/gperftools-2.1/.libs"
echo "DYLD_LIBRARY_PATH=${BASE_DIR}/src/third_party/gperftools-2.1/.libs"
export LD_PRELOAD="${BASE_DIR}/src/third_party/gperftools-2.1/.libs/libtcmalloc_minimal.so.4"
echo "LD_PRELOAD=${BASE_DIR}/src/third_party/gperftools-2.1/.libs/libtcmalloc_minimal.so.4"
exit
